In [1]:
import re
import pandas as pd

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

In [2]:
f = open('WhatsApp Chat with Apne Group 😎.txt','r',encoding = 'utf-8')

In [3]:
data = f.read()

In [4]:
data

'09/08/25, 10:26\u202fpm - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*\n17/10/22, 1:56\u202fam - Mohit Nmh ME Tu created group "Apne Group 😎"\n17/10/22, 1:56\u202fam - You were added\n16/08/25, 2:19\u202fpm - RAUSHAN Raj Tezpur: Happy Birthday to you 🎉🥳🥳🥳@\u2068Himanshu Kumar\u2069\n16/08/25, 2:27\u202fpm - Shwetank Tezpur: Happy birthday 🎉🎂🎈 @\u2068Himanshu Kumar\u2069\n16/08/25, 6:04\u202fpm - Himanshu Kumar: Thanks bhai ✨🫂🫂\n16/08/25, 6:04\u202fpm - Himanshu Kumar: Thanks bhai 🫂✨✨\n16/08/25, 6:15\u202fpm - Utkarsh Tu: happy birthday selmon bhai ✨🥂\n16/08/25, 6:19\u202fpm - Rohan Gupta EE Tu: Happy birthday  @\u2068Himanshu Kumar\u2069 bhai ✨✨\n16/08/25, 7:01\u202fpm - Shourya Ece Tu: Happy Birthday  bro @\u2068Himanshu Kumar\u2069 , enjoy 🔥\n16/08/25, 7:16\u202fpm - Sushil Tu: Happy birthday @\u2068Himanshu Kumar\u2069\n16/08/25, 7:26\u202fpm - Rohit Singh ECE NMH TU: Happy birthday @\u2068Himanshu Kumar\u2069 🎂🎉🎁 Party toh banta hai Bhai\n16/08/25, 8:09\u202fpm - Rupesh (CSE) Tmh Tu: Happy Birthday @\u2068Himanshu Kumar\u2069   \nVikas bol rha tha Himanshu ke shadi ka baat chl rha hai 😃 .\n16/08/25, 8:09\u202fpm - Rupesh (CSE) Tmh Tu: Happy Marriage in Advance 🥳🥳\n16/08/25, 8:15\u202fpm - Somesh ECE Kmh Tu: Happy Birthday 🎉🎈🎂🎉@\u2068Himanshu Kumar\u2069\n16/08/25, 8:45\u202fpm - Robin ranjan Civil Nmh Tu: Happy Birthday @\u2068Himanshu Kumar\u2069  bhai 🥳🥳🥳\n16/08/25, 9:05\u202fpm - Himanshu Kumar: Thanks bhai log 🫂🥹✨ wish karne ke liyw\n16/08/25, 9:06\u202fpm - Himanshu Kumar: Abhi hostel me hote ham log to kya maja karte gand faar\n16/08/25, 9:07\u202fpm - Rohit Singh ECE NMH TU: Tera gand farte bhai aur kya karte\n16/08/25, 9:08\u202fpm - Himanshu Kumar: 🤣🤣\n16/08/25, 9:19\u202fpm - Prashun Tu: Yhi sala fartaa\n16/08/25, 9:20\u202fpm - Amit Tu: Happy birthday @\u2068Himanshu Kumar\u2069 🎂🍌🍌🍒🍒\n16/08/25, 9:21\u202fpm - Prashun Tu: Happy Birthday @\u2068Himanshu Kumar\u2069 brother 💦💦🎂🥳\n16/08/25, 9:22\u202fpm - Vìvèk Tezpur Cse: Happy birthday @\u2068Himanshu Kumar\u2069 🍾🍾\n16/08/25, 9:22\u202fpm - Amit Tu: Ye banana ko upper or apple ko niche kaise kr skte hai 🍌🍒\n16/08/25, 9:31\u202fpm - Shwetank Tezpur: 🍒\n🍌\n16/08/25, 9:31\u202fpm - Shwetank Tezpur: Ye lo\n16/08/25, 9:34\u202fpm - Amit Tu: Ulta kro 😅\n16/08/25, 9:35\u202fpm - Shwetank Tezpur: 🍌\n🍒\n16/08/25, 9:35\u202fpm - Shwetank Tezpur: 🫡\n16/08/25, 10:08\u202fpm - Himanshu Kumar: Thanks bhailog 🙏😊🫂✨\n16/08/25, 10:54\u202fpm - Ayush Ranjan Tezpur Civil: Happy birthday 🎂 🥳 🎉 🎈 jii @\u2068Himanshu Kumar\u2069\n16/08/25, 11:44\u202fpm - Himanshu Kumar: Thank u neta jii 🫂✨\n20/08/25, 1:12\u202fpm - Rohan Gupta EE Tu: <Media omitted>\n20/08/25, 1:12\u202fpm - Mohit Nmh ME Tu: This message was deleted\n20/08/25, 1:12\u202fpm - Mohit Nmh ME Tu: Nhi 22\n20/08/25, 1:17\u202fpm - Rohan Gupta EE Tu: Bhai ye sab kya ho raha hai\n20/08/25, 1:17\u202fpm - Rohan Gupta EE Tu: 🫥\n20/08/25, 1:29\u202fpm - Somesh ECE Kmh Tu: 2025\n20/08/25, 3:30\u202fpm - Srinivash CSE Pmh Tu: 22\n23/08/25, 10:43\u202fpm - Aryan Kmh Tu changed their phone number to a new number. Message or add the new number\n30/09/25, 5:51\u202fpm - Srinivash CSE Pmh Tu: Happy Birthday (belated) @\u2068Suraj Tezpur\u2069\n30/09/25, 5:51\u202fpm - Srinivash CSE Pmh Tu: <Media omitted>\n30/09/25, 5:55\u202fpm - Rohan Gupta EE Tu: Happy birthday @\u2068Suraj Tezpur\u2069 💋💋\n30/09/25, 6:00\u202fpm - Amit Tu: Happy birthday🎂🎉🎁@\u2068Suraj Tezpur\u2069\n30/09/25, 6:36\u202fpm - Shwetank Tezpur: Happy birthday @\u2068Suraj Tezpur\u2069  😍 🥙 🍔 🍿 😋🐪\n30/09/25, 7:08\u202fpm - Shourya Ece Tu: Happy Birthday @\u2068Suraj Tezpur\u2069  🔥✌️🎂✨️\n30/09/25, 11:12\u202fpm - Utkarsh Tu: happy birthday Suraj ✨\n30/09/25, 11:21\u202fpm - Suraj Tezpur: Thank you so much everyone...😀\n30/09/25, 11:27\u202fpm - Himanshu Kumar: Happy birthday @\u2068Suraj Tezpur\u2069  🎂🎂🎈🎈🥳🧁\n01/10/25, 8:47\u202fam - Rupesh (CSE) Tmh Tu: Happy Birthday @\u2068Suraj Tezpur\u2069  ✨✨🥳🥳😎\n01/10/25, 10:32\u202fpm - Suraj Tezpur: Thank you himanshu and rupesh 🙂\n04/11/25, 9:59\u202fpm - Srinivash CSE Pmh Tu: Caution money agaya kya sabka ?\n05/11/25, 12:04\u202fam - Nitish Civil Kmh Tu: Nhi <This message was edited>\n20/11/25, 9:11\u202fpm - Somesh ECE Kmh Tu: Happy Birthday 🎂🎉🎂🎂🎉🎈🎁🎉🎉🎂 @\u2068RAUSHAN Raj Tezpur\u2069\n20/11/25, 9:26\u202fpm - Rohan Gupta EE Tu: Happy birthday @\u2068RAUSHAN Raj Tezpur\u2069 ✨✨\n20/11/25, 9:49\u202fpm - RAUSHAN Raj Tezpur: Thank you very much\n01/01/26, 10:37\u202fam - Md Imran Ee Tmh Tu: Happy new year🎉\nBhai log ✨\n01/01/26, 10:52\u202fam - RAUSHAN Raj Tezpur: <Media omitted>\n01/01/26, 11:46\u202fam - Himanshu Kumar: Happy new year brothers ✨🫂💫🎉\n01/01/26, 11:47\u202fam - Shwetank Tezpur: Happpy New Year Bhailogwaa 🎊🎊🎊🎆\n01/01/26, 12:38\u202fpm - Rohit Singh ECE NMH TU: Happy New year Everyone 🎇🎆\n01/01/26, 1:12\u202fpm - Amit Tu: Happy birthday to 2026 🥳\n27/02/26, 11:54\u202fam - RAUSHAN Raj Tezpur: <Media omitted>\n27/02/26, 12:12\u202fpm - RAUSHAN Raj Tezpur: POLL:\nConvocation me jayenge\nOPTION: Yes (10 votes)\nOPTION: Not sure (6 votes)\n\n28/02/26, 9:05\u202fam - Rupesh (CSE) Tmh Tu: late bta rhe hai ye log, mujhe lga ki summer vacations me hoga\n28/02/26, 10:18\u202fam - RAUSHAN Raj Tezpur: Sushil aa rha hai\n28/02/26, 10:28\u202fam - Amit Tu: This message was deleted\n28/02/26, 10:36\u202fam - Srinivash CSE Pmh Tu: 23 ho convocation h, to 24 to kisi ko rahne dega university me ?\n28/02/26, 11:00\u202fam - RAUSHAN Raj Tezpur: Ha\n28/02/26, 11:01\u202fam - Amit Tu: Raushan scooty kb bechega\n28/02/26, 11:01\u202fam - RAUSHAN Raj Tezpur: Bech diye hai\n28/02/26, 11:01\u202fam - RAUSHAN Raj Tezpur: Already\n28/02/26, 11:02\u202fam - Amit Tu: Convo me kaun aa rha h Bada aadmi\n28/02/26, 11:03\u202fam - Amit Tu: Degree dene\n28/02/26, 11:03\u202fam - RAUSHAN Raj Tezpur: Pijush chacha\n28/02/26, 11:04\u202fam - Amit Tu: Panauti\n28/02/26, 11:29\u202fam - Suraj Tezpur: trevellung peln kay hia tomlug ka?\n28/02/26, 11:29\u202fam - Suraj Tezpur: 24 ku bapus jaoge na?\n28/02/26, 11:45\u202fam - Amit Tu: Depend kaun kaha h Or kitna time spent krna chahta h dost me sath\n28/02/26, 12:08\u202fpm - Suraj Tezpur: ha ysi ku to plan kehte hai wrna baki sb moh maia h\n28/02/26, 12:15\u202fpm - RAUSHAN Raj Tezpur: Hyderabad se biryani lete aana\n28/02/26, 12:16\u202fpm - Mohit Nmh ME Tu: Kab tak pahunchna hai college\n28/02/26, 12:17\u202fpm - Suraj Tezpur: aap kahan h\n28/02/26, 12:17\u202fpm - Amit Tu: Aap... Mtlb?\n28/02/26, 12:17\u202fpm - RAUSHAN Raj Tezpur: Aapke dil me\n28/02/26, 12:17\u202fpm - Amit Tu: 😂😂🍌\n28/02/26, 12:17\u202fpm - RAUSHAN Raj Tezpur: Tumhara dil ka structure thora casual hai\n28/02/26, 12:18\u202fpm - Mohit Nmh ME Tu: 😘\n28/02/26, 12:18\u202fpm - Amit Tu: 😂😂\n28/02/26, 12:18\u202fpm - Suraj Tezpur: arey apka job location?\n28/02/26, 12:18\u202fpm - RAUSHAN Raj Tezpur: Haryana\n28/02/26, 12:19\u202fpm - Suraj Tezpur: 😟\n28/02/26, 12:21\u202fpm - RAUSHAN Raj Tezpur: Tha\n28/02/26, 12:21\u202fpm - RAUSHAN Raj Tezpur: Thailand chalna hai\n28/02/26, 12:22\u202fpm - Amit Tu: Mujhe bhi jana h... Jaoge to bolna <This message was edited>\n28/02/26, 12:22\u202fpm - RAUSHAN Raj Tezpur: Chailand*\n28/02/26, 12:22\u202fpm - RAUSHAN Raj Tezpur: https://www.linkedin.com/posts/drvijayendersingh_upspcbrecruitment-upspcbjobs-aeeupspcb-activity-7433347188547805184-V994?utm_source=li_share&utm_content=feedcontent&utm_medium=g_mb_web&utm_campaign=copy\n28/02/26, 12:23\u202fpm - Amit Tu: @\u2068Mithun Tezpur Ee Tu\u2069 kaha ho bhai?\n28/02/26, 12:23\u202fpm - RAUSHAN Raj Tezpur: Somesh ke dil me\n28/02/26, 12:25\u202fpm - Amit Tu: Somesh ashik hai ya Somesh ka ashik h\n28/02/26, 3:59\u202fpm - Mithun Tezpur Ee Tu: @\u2068RAUSHAN Raj Tezpur\u2069 @\u2068Amit Tu\u2069 ja raha h ki nhi convocation m\n28/02/26, 4:00\u202fpm - RAUSHAN Raj Tezpur: Ha\n28/02/26, 4:58\u202fpm - Amit Tu: Ha .. Kb aa rha h?\n28/02/26, 5:05\u202fpm - Mithun Tezpur Ee Tu: 21\n28/02/26, 5:08\u202fpm - Amit Tu: Kaha?\n28/02/26, 5:09\u202fpm - Mithun Tezpur Ee Tu: This message was deleted\n28/02/26, 5:09\u202fpm - Mithun Tezpur Ee Tu: Convoc\n28/02/26, 5:09\u202fpm - Amit Tu: Kb se kb ka stay dega wo log?\n28/02/26, 5:10\u202fpm - Mithun Tezpur Ee Tu: Relax abhi bahut din h apne batayega\n28/02/26, 5:10\u202fpm - Rohan Gupta EE Tu: Stay nahi dega shyd\n28/02/26, 5:10\u202fpm - Amit Tu: Kyu?\n28/02/26, 5:12\u202fpm - Rohan Gupta EE Tu: Jagha kaha hai\n28/02/26, 5:12\u202fpm - Mithun Tezpur Ee Tu: Bihu hoga sayad uss samay m\n28/02/26, 5:31\u202fpm - Nitish Civil Kmh Tu: Tm krega na?\n28/02/26, 5:33\u202fpm - Mithun Tezpur Ee Tu: @\u2068Nitish Civil Kmh Tu\u2069 ke room m jagah h\n28/02/26, 5:33\u202fpm - Mithun Tezpur Ee Tu: @\u2068Rohan Gupta EE Tu\u2069\n28/02/26, 5:34\u202fpm - Nitish Civil Kmh Tu: Haa ekdum aao to pahle tm\n28/02/26, 5:34\u202fpm - Nitish Civil Kmh Tu: Bs POL dance kr dena <This message was edited>\n28/02/26, 5:34\u202fpm - Mithun Tezpur Ee Tu: Karwayenge\n28/02/26, 5:35\u202fpm - Nitish Civil Kmh Tu: Aa pahle tm\n28/02/26, 5:36\u202fpm - Amit Tu: @\u2068Nitish Civil Kmh Tu\u2069  kya haal chaal hai\n28/02/26, 5:45\u202fpm - Nitish Civil Kmh Tu: Kuttu paratha\n09/03/26, 5:18\u202fpm - RAUSHAN Raj Tezpur: <Media omitted>\n09/03/26, 5:18\u202fpm - RAUSHAN Raj Tezpur: @\u2068Vikash Ece PMH Tu\u2069 @\u2068Himanshu Kumar\u2069\n09/03/26, 5:18\u202fpm - RAUSHAN Raj Tezpur: @all\n09/03/26, 5:23\u202fpm - Mohit Nmh ME Tu: Ye to alag hi level ka banda hai\n09/03/26, 5:29\u202fpm - Amit Tu: Ha dulha h 😎😊\n09/03/26, 5:39\u202fpm - Prashun Tu: Bahinchod\n09/03/26, 5:40\u202fpm - Mohit Nmh ME Tu: <Media omitted>\n09/03/26, 5:41\u202fpm - Amit Tu: Bhai fielding se bachna 😅\n09/03/26, 5:42\u202fpm - Prashun Tu: Dahej liya h ab fielding me koi nhi h sala dhouda kr pelega <This message was edited>\n09/03/26, 5:45\u202fpm - Prashun Tu: Fielding to bs ek aadmi hi set krta tha @\u2068Robin ranjan Civil Nmh Tu\u2069\n09/03/26, 5:47\u202fpm - Amit Tu: Bhai gadi ka licence hai n 😅\n09/03/26, 5:48\u202fpm - Amit Tu: Ya Robin ke paas h 😂\n09/03/26, 6:24\u202fpm - Srinivash CSE Pmh Tu: Sadi ho rahi h dono ki\n09/03/26, 6:26\u202fpm - RAUSHAN Raj Tezpur: Per chhauri kon h\n09/03/26, 6:26\u202fpm - Srinivash CSE Pmh Tu: Ye log apas me discuss kar lega, hame kya😅\n09/03/26, 6:46\u202fpm - RAUSHAN Raj Tezpur: <Media omitted>\n10/03/26, 11:23\u202fam - RAUSHAN Raj Tezpur: Confirm hogaya hai\nVikash ka shaadi nhi ho rha hai\n10/03/26, 11:23\u202fam - RAUSHAN Raj Tezpur: Uske bhaiya ka shaadi hai\n10/03/26, 11:23\u202fam - Mohit Nmh ME Tu: Hm\n11/03/26, 9:53\u202fpm - RAUSHAN Raj Tezpur: https://docs.google.com/forms/d/e/1FAIpQLSfxEgfhJSv48YrJnfMRUPt5pkfA1YVhKw1GllTHmQAvTAC_nA/viewform\n11/03/26, 9:53\u202fpm - RAUSHAN Raj Tezpur: Sab bhar do\n11/03/26, 9:53\u202fpm - RAUSHAN Raj Tezpur: Jo Jo nhi bhara hai\n15/03/26, 1:42\u202fpm - RAUSHAN Raj Tezpur: Aaj last date hai\n16/03/26, 4:45\u202fpm - RAUSHAN Raj Tezpur: Kon kon ticket kaant liya hai tu jaane ka\n16/03/26, 4:46\u202fpm - Kush Kumar Tu: Tatkal me Dekha jaayega Mera\n16/03/26, 4:54\u202fpm - RAUSHAN Raj Tezpur: <Media omitted>\n16/03/26, 5:18\u202fpm - Sushil Tu: Tum zinda hai abhi tk\n16/03/26, 5:23\u202fpm - RAUSHAN Raj Tezpur: Tum kya chhahte ho\n16/03/26, 6:06\u202fpm - Rohan Gupta EE Tu: <Media omitted>\n16/03/26, 6:06\u202fpm - Rohan Gupta EE Tu: Maderchod sale\n16/03/26, 6:08\u202fpm - RAUSHAN Raj Tezpur: <Media omitted>\n16/03/26, 6:08\u202fpm - RAUSHAN Raj Tezpur: Larchat administration\n16/03/26, 6:08\u202fpm - RAUSHAN Raj Tezpur: Election pe blame daal diya\n17/03/26, 3:06\u202fpm - Suraj Tezpur: Amazon prime h kisi k pass?@\u2068RAUSHAN Raj Tezpur\u2069\n17/03/26, 3:06\u202fpm - Suraj Tezpur: ek order Krna tha bs\n17/03/26, 4:50\u202fpm - RAUSHAN Raj Tezpur: Abhi to nhi hai 😔\n17/03/26, 7:48\u202fpm - Suraj Tezpur: it\'s ok luv u😘\n23/03/26, 11:32\u202fam - Nitish Civil Kmh Tu: Happy convocation 😊\n23/03/26, 11:27\u202fpm - Nitish Civil Kmh Tu: <Media omitted>\n23/03/26, 11:27\u202fpm - Nitish Civil Kmh Tu: <Media omitted>\n23/03/26, 11:46\u202fpm - Amit Tu: Kya mila?\n24/03/26, 12:10\u202fam - Himanshu Kumar: <Media omitted>\n24/03/26, 12:34\u202fam - Nitish Civil Kmh Tu: 🤏🏻\n25/03/26, 11:28\u202fam - Amit Tu: This message was deleted\n25/04/26, 12:50\u202fam - RAUSHAN Raj Tezpur: Patna me kon kon hai abhi\n25/04/26, 1:37\u202fam - Nitish Civil Kmh Tu: Mai hu\n25/04/26, 1:38\u202fam - RAUSHAN Raj Tezpur: <Media omitted>\n25/04/26, 1:38\u202fam - RAUSHAN Raj Tezpur: To aao chicken Puri khaane\n25/04/26, 1:39\u202fam - Nitish Civil Kmh Tu: Kidhar pauch gya be\n25/04/26, 8:00\u202fpm - Himanshu Kumar: Aaye the To banaya bhi sala\n26/04/26, 4:27\u202fpm - RAUSHAN Raj Tezpur: <Media omitted>\n26/04/26, 4:40\u202fpm - Amit Tu: Cctv se photo click kiye ho kya..😅\n26/04/26, 5:02\u202fpm - RAUSHAN Raj Tezpur: Live hai\n29/06/26, 7:03\u202fpm - Himanshu Kumar: Abhi Patna me koi rah raha hai kya ??\n29/06/26, 9:31\u202fpm - RAUSHAN Raj Tezpur: Samrat choudhary\n29/06/26, 10:29\u202fpm - Amit Tu: Ek baar phir se Nitish Sarkar\n'

In [5]:
print(data)

09/08/25, 10:26 pm - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*
17/10/22, 1:56 am - Mohit Nmh ME Tu created group "Apne Group 😎"
17/10/22, 1:56 am - You were added
16/08/25, 2:19 pm - RAUSHAN Raj Tezpur: Happy Birthday to you 🎉🥳🥳🥳@⁨Himanshu Kumar⁩
16/08/25, 2:27 pm - Shwetank Tezpur: Happy birthday 🎉🎂🎈 @⁨Himanshu Kumar⁩
16/08/25, 6:04 pm - Himanshu Kumar: Thanks bhai ✨🫂🫂
16/08/25, 6:04 pm - Himanshu Kumar: Thanks bhai 🫂✨✨
16/08/25, 6:15 pm - Utkarsh Tu: happy birthday selmon bhai ✨🥂
16/08/25, 6:19 pm - Rohan Gupta EE Tu: Happy birthday  @⁨Himanshu Kumar⁩ bhai ✨✨
16/08/25, 7:01 pm - Shourya Ece Tu: Happy Birthday  bro @⁨Himanshu Kumar⁩ , enjoy 🔥
16/08/25, 7:16 pm - Sushil Tu: Happy birthday @⁨Himanshu Kumar⁩
16/08/25, 7:26 pm - Rohit Singh ECE NMH TU: Happy birthday @⁨Himanshu Kumar⁩ 🎂🎉🎁 Party toh banta hai Bhai
16/08/25, 8:09 pm - Rupesh (CSE) Tmh Tu: Happy Birthday @⁨Himanshu Kumar⁩
Vikas bol rha tha Himanshu ke shadi ka baat chl rha hai 😃 .
16/08/25, 8:09 pm - Rupesh (CSE) Tmh Tu: Happy Marriage in Advance 🥳🥳
16/08/25, 8:15 pm - Somesh ECE Kmh Tu: Happy Birthday 🎉🎈🎂🎉@⁨Himanshu Kumar⁩
16/08/25, 8:45 pm - Robin ranjan Civil Nmh Tu: Happy Birthday @⁨Himanshu Kumar⁩  bhai 🥳🥳🥳
16/08/25, 9:05 pm - Himanshu Kumar: Thanks bhai log 🫂🥹✨ wish karne ke liyw
16/08/25, 9:06 pm - Himanshu Kumar: Abhi hostel me hote ham log to kya maja karte gand faar
16/08/25, 9:07 pm - Rohit Singh ECE NMH TU: Tera gand farte bhai aur kya karte
16/08/25, 9:08 pm - Himanshu Kumar: 🤣🤣
16/08/25, 9:19 pm - Prashun Tu: Yhi sala fartaa
16/08/25, 9:20 pm - Amit Tu: Happy birthday @⁨Himanshu Kumar⁩ 🎂🍌🍌🍒🍒
16/08/25, 9:21 pm - Prashun Tu: Happy Birthday @⁨Himanshu Kumar⁩ brother 💦💦🎂🥳
16/08/25, 9:22 pm - Vìvèk Tezpur Cse: Happy birthday @⁨Himanshu Kumar⁩ 🍾🍾
16/08/25, 9:22 pm - Amit Tu: Ye banana ko upper or apple ko niche kaise kr skte hai 🍌🍒
16/08/25, 9:31 pm - Shwetank Tezpur: 🍒
🍌
16/08/25, 9:31 pm - Shwetank Tezpur: Ye lo
16/08/25, 9:34 pm - Amit Tu: Ulta kro 😅
16/08/25, 9:35 pm - Shwetank Tezpur: 🍌
🍒
16/08/25, 9:35 pm - Shwetank Tezpur: 🫡
16/08/25, 10:08 pm - Himanshu Kumar: Thanks bhailog 🙏😊🫂✨
16/08/25, 10:54 pm - Ayush Ranjan Tezpur Civil: Happy birthday 🎂 🥳 🎉 🎈 jii @⁨Himanshu Kumar⁩
16/08/25, 11:44 pm - Himanshu Kumar: Thank u neta jii 🫂✨
20/08/25, 1:12 pm - Rohan Gupta EE Tu: <Media omitted>
20/08/25, 1:12 pm - Mohit Nmh ME Tu: This message was deleted
20/08/25, 1:12 pm - Mohit Nmh ME Tu: Nhi 22
20/08/25, 1:17 pm - Rohan Gupta EE Tu: Bhai ye sab kya ho raha hai
20/08/25, 1:17 pm - Rohan Gupta EE Tu: 🫥
20/08/25, 1:29 pm - Somesh ECE Kmh Tu: 2025
20/08/25, 3:30 pm - Srinivash CSE Pmh Tu: 22
23/08/25, 10:43 pm - Aryan Kmh Tu changed their phone number to a new number. Message or add the new number
30/09/25, 5:51 pm - Srinivash CSE Pmh Tu: Happy Birthday (belated) @⁨Suraj Tezpur⁩
30/09/25, 5:51 pm - Srinivash CSE Pmh Tu: <Media omitted>
30/09/25, 5:55 pm - Rohan Gupta EE Tu: Happy birthday @⁨Suraj Tezpur⁩ 💋💋
30/09/25, 6:00 pm - Amit Tu: Happy birthday🎂🎉🎁@⁨Suraj Tezpur⁩
30/09/25, 6:36 pm - Shwetank Tezpur: Happy birthday @⁨Suraj Tezpur⁩  😍 🥙 🍔 🍿 😋🐪
30/09/25, 7:08 pm - Shourya Ece Tu: Happy Birthday @⁨Suraj Tezpur⁩  🔥✌️🎂✨️
30/09/25, 11:12 pm - Utkarsh Tu: happy birthday Suraj ✨
30/09/25, 11:21 pm - Suraj Tezpur: Thank you so much everyone...😀
30/09/25, 11:27 pm - Himanshu Kumar: Happy birthday @⁨Suraj Tezpur⁩  🎂🎂🎈🎈🥳🧁
01/10/25, 8:47 am - Rupesh (CSE) Tmh Tu: Happy Birthday @⁨Suraj Tezpur⁩  ✨✨🥳🥳😎
01/10/25, 10:32 pm - Suraj Tezpur: Thank you himanshu and rupesh 🙂
04/11/25, 9:59 pm - Srinivash CSE Pmh Tu: Caution money agaya kya sabka ?
05/11/25, 12:04 am - Nitish Civil Kmh Tu: Nhi <This message was edited>
20/11/25, 9:11 pm - Somesh ECE Kmh Tu: Happy Birthday 🎂🎉🎂🎂🎉🎈🎁🎉🎉🎂 @⁨RAUSHAN Raj Tezpur⁩
20/11/25, 9:26 pm - Rohan Gupta EE Tu: Happy birthday @⁨RAUSHAN Raj Tezpur⁩ ✨✨
20/11/25, 9:49 pm - RAUSHAN Raj Tezpur: Thank you very much
01/01/26, 10:37 am - Md Imran Ee Tmh Tu: Happy new year🎉
Bhai log ✨
01/01/26, 10:52 am - RAUSHAN Raj Tezpur: <Media omitted>
01/01/26, 11:46 am - Himanshu Kumar: Happy new year brothers ✨🫂💫🎉
01/01/26, 11:47 am - Shwetank Tezpur: Happpy New Year Bhailogwaa 🎊🎊🎊🎆
01/01/26, 12:38 pm - Rohit Singh ECE NMH TU: Happy New year Everyone 🎇🎆
01/01/26, 1:12 pm - Amit Tu: Happy birthday to 2026 🥳
27/02/26, 11:54 am - RAUSHAN Raj Tezpur: <Media omitted>
27/02/26, 12:12 pm - RAUSHAN Raj Tezpur: POLL:
Convocation me jayenge
OPTION: Yes (10 votes)
OPTION: Not sure (6 votes)

28/02/26, 9:05 am - Rupesh (CSE) Tmh Tu: late bta rhe hai ye log, mujhe lga ki summer vacations me hoga
28/02/26, 10:18 am - RAUSHAN Raj Tezpur: Sushil aa rha hai
28/02/26, 10:28 am - Amit Tu: This message was deleted
28/02/26, 10:36 am - Srinivash CSE Pmh Tu: 23 ho convocation h, to 24 to kisi ko rahne dega university me ?
28/02/26, 11:00 am - RAUSHAN Raj Tezpur: Ha
28/02/26, 11:01 am - Amit Tu: Raushan scooty kb bechega
28/02/26, 11:01 am - RAUSHAN Raj Tezpur: Bech diye hai
28/02/26, 11:01 am - RAUSHAN Raj Tezpur: Already
28/02/26, 11:02 am - Amit Tu: Convo me kaun aa rha h Bada aadmi
28/02/26, 11:03 am - Amit Tu: Degree dene
28/02/26, 11:03 am - RAUSHAN Raj Tezpur: Pijush chacha
28/02/26, 11:04 am - Amit Tu: Panauti
28/02/26, 11:29 am - Suraj Tezpur: trevellung peln kay hia tomlug ka?
28/02/26, 11:29 am - Suraj Tezpur: 24 ku bapus jaoge na?
28/02/26, 11:45 am - Amit Tu: Depend kaun kaha h Or kitna time spent krna chahta h dost me sath
28/02/26, 12:08 pm - Suraj Tezpur: ha ysi ku to plan kehte hai wrna baki sb moh maia h
28/02/26, 12:15 pm - RAUSHAN Raj Tezpur: Hyderabad se biryani lete aana
28/02/26, 12:16 pm - Mohit Nmh ME Tu: Kab tak pahunchna hai college
28/02/26, 12:17 pm - Suraj Tezpur: aap kahan h
28/02/26, 12:17 pm - Amit Tu: Aap... Mtlb?
28/02/26, 12:17 pm - RAUSHAN Raj Tezpur: Aapke dil me
28/02/26, 12:17 pm - Amit Tu: 😂😂🍌
28/02/26, 12:17 pm - RAUSHAN Raj Tezpur: Tumhara dil ka structure thora casual hai
28/02/26, 12:18 pm - Mohit Nmh ME Tu: 😘
28/02/26, 12:18 pm - Amit Tu: 😂😂
28/02/26, 12:18 pm - Suraj Tezpur: arey apka job location?
28/02/26, 12:18 pm - RAUSHAN Raj Tezpur: Haryana
28/02/26, 12:19 pm - Suraj Tezpur: 😟
28/02/26, 12:21 pm - RAUSHAN Raj Tezpur: Tha
28/02/26, 12:21 pm - RAUSHAN Raj Tezpur: Thailand chalna hai
28/02/26, 12:22 pm - Amit Tu: Mujhe bhi jana h... Jaoge to bolna <This message was edited>
28/02/26, 12:22 pm - RAUSHAN Raj Tezpur: Chailand*
28/02/26, 12:22 pm - RAUSHAN Raj Tezpur: https://www.linkedin.com/posts/drvijayendersingh_upspcbrecruitment-upspcbjobs-aeeupspcb-activity-7433347188547805184-V994?utm_source=li_share&utm_content=feedcontent&utm_medium=g_mb_web&utm_campaign=copy
28/02/26, 12:23 pm - Amit Tu: @⁨Mithun Tezpur Ee Tu⁩ kaha ho bhai?
28/02/26, 12:23 pm - RAUSHAN Raj Tezpur: Somesh ke dil me
28/02/26, 12:25 pm - Amit Tu: Somesh ashik hai ya Somesh ka ashik h
28/02/26, 3:59 pm - Mithun Tezpur Ee Tu: @⁨RAUSHAN Raj Tezpur⁩ @⁨Amit Tu⁩ ja raha h ki nhi convocation m
28/02/26, 4:00 pm - RAUSHAN Raj Tezpur: Ha
28/02/26, 4:58 pm - Amit Tu: Ha .. Kb aa rha h?
28/02/26, 5:05 pm - Mithun Tezpur Ee Tu: 21
28/02/26, 5:08 pm - Amit Tu: Kaha?
28/02/26, 5:09 pm - Mithun Tezpur Ee Tu: This message was deleted
28/02/26, 5:09 pm - Mithun Tezpur Ee Tu: Convoc
28/02/26, 5:09 pm - Amit Tu: Kb se kb ka stay dega wo log?
28/02/26, 5:10 pm - Mithun Tezpur Ee Tu: Relax abhi bahut din h apne batayega
28/02/26, 5:10 pm - Rohan Gupta EE Tu: Stay nahi dega shyd
28/02/26, 5:10 pm - Amit Tu: Kyu?
28/02/26, 5:12 pm - Rohan Gupta EE Tu: Jagha kaha hai
28/02/26, 5:12 pm - Mithun Tezpur Ee Tu: Bihu hoga sayad uss samay m
28/02/26, 5:31 pm - Nitish Civil Kmh Tu: Tm krega na?
28/02/26, 5:33 pm - Mithun Tezpur Ee Tu: @⁨Nitish Civil Kmh Tu⁩ ke room m jagah h
28/02/26, 5:33 pm - Mithun Tezpur Ee Tu: @⁨Rohan Gupta EE Tu⁩
28/02/26, 5:34 pm - Nitish Civil Kmh Tu: Haa ekdum aao to pahle tm
28/02/26, 5:34 pm - Nitish Civil Kmh Tu: Bs POL dance kr dena <This message was edited>
28/02/26, 5:34 pm - Mithun Tezpur Ee Tu: Karwayenge
28/02/26, 5:35 pm - Nitish Civil Kmh Tu: Aa pahle tm
28/02/26, 5:36 pm - Amit Tu: @⁨Nitish Civil Kmh Tu⁩  kya haal chaal hai
28/02/26, 5:45 pm - Nitish Civil Kmh Tu: Kuttu paratha
09/03/26, 5:18 pm - RAUSHAN Raj Tezpur: <Media omitted>
09/03/26, 5:18 pm - RAUSHAN Raj Tezpur: @⁨Vikash Ece PMH Tu⁩ @⁨Himanshu Kumar⁩
09/03/26, 5:18 pm - RAUSHAN Raj Tezpur: @all
09/03/26, 5:23 pm - Mohit Nmh ME Tu: Ye to alag hi level ka banda hai
09/03/26, 5:29 pm - Amit Tu: Ha dulha h 😎😊
09/03/26, 5:39 pm - Prashun Tu: Bahinchod
09/03/26, 5:40 pm - Mohit Nmh ME Tu: <Media omitted>
09/03/26, 5:41 pm - Amit Tu: Bhai fielding se bachna 😅
09/03/26, 5:42 pm - Prashun Tu: Dahej liya h ab fielding me koi nhi h sala dhouda kr pelega <This message was edited>
09/03/26, 5:45 pm - Prashun Tu: Fielding to bs ek aadmi hi set krta tha @⁨Robin ranjan Civil Nmh Tu⁩
09/03/26, 5:47 pm - Amit Tu: Bhai gadi ka licence hai n 😅
09/03/26, 5:48 pm - Amit Tu: Ya Robin ke paas h 😂
09/03/26, 6:24 pm - Srinivash CSE Pmh Tu: Sadi ho rahi h dono ki
09/03/26, 6:26 pm - RAUSHAN Raj Tezpur: Per chhauri kon h
09/03/26, 6:26 pm - Srinivash CSE Pmh Tu: Ye log apas me discuss kar lega, hame kya😅
09/03/26, 6:46 pm - RAUSHAN Raj Tezpur: <Media omitted>
10/03/26, 11:23 am - RAUSHAN Raj Tezpur: Confirm hogaya hai
Vikash ka shaadi nhi ho rha hai
10/03/26, 11:23 am - RAUSHAN Raj Tezpur: Uske bhaiya ka shaadi hai
10/03/26, 11:23 am - Mohit Nmh ME Tu: Hm
11/03/26, 9:53 pm - RAUSHAN Raj Tezpur: https://docs.google.com/forms/d/e/1FAIpQLSfxEgfhJSv48YrJnfMRUPt5pkfA1YVhKw1GllTHmQAvTAC_nA/viewform
11/03/26, 9:53 pm - RAUSHAN Raj Tezpur: Sab bhar do
11/03/26, 9:53 pm - RAUSHAN Raj Tezpur: Jo Jo nhi bhara hai
15/03/26, 1:42 pm - RAUSHAN Raj Tezpur: Aaj last date hai
16/03/26, 4:45 pm - RAUSHAN Raj Tezpur: Kon kon ticket kaant liya hai tu jaane ka
16/03/26, 4:46 pm - Kush Kumar Tu: Tatkal me Dekha jaayega Mera
16/03/26, 4:54 pm - RAUSHAN Raj Tezpur: <Media omitted>
16/03/26, 5:18 pm - Sushil Tu: Tum zinda hai abhi tk
16/03/26, 5:23 pm - RAUSHAN Raj Tezpur: Tum kya chhahte ho
16/03/26, 6:06 pm - Rohan Gupta EE Tu: <Media omitted>
16/03/26, 6:06 pm - Rohan Gupta EE Tu: Maderchod sale
16/03/26, 6:08 pm - RAUSHAN Raj Tezpur: <Media omitted>
16/03/26, 6:08 pm - RAUSHAN Raj Tezpur: Larchat administration
16/03/26, 6:08 pm - RAUSHAN Raj Tezpur: Election pe blame daal diya
17/03/26, 3:06 pm - Suraj Tezpur: Amazon prime h kisi k pass?@⁨RAUSHAN Raj Tezpur⁩
17/03/26, 3:06 pm - Suraj Tezpur: ek order Krna tha bs
17/03/26, 4:50 pm - RAUSHAN Raj Tezpur: Abhi to nhi hai 😔
17/03/26, 7:48 pm - Suraj Tezpur: it's ok luv u😘
23/03/26, 11:32 am - Nitish Civil Kmh Tu: Happy convocation 😊
23/03/26, 11:27 pm - Nitish Civil Kmh Tu: <Media omitted>
23/03/26, 11:27 pm - Nitish Civil Kmh Tu: <Media omitted>
23/03/26, 11:46 pm - Amit Tu: Kya mila?
24/03/26, 12:10 am - Himanshu Kumar: <Media omitted>
24/03/26, 12:34 am - Nitish Civil Kmh Tu: 🤏🏻
25/03/26, 11:28 am - Amit Tu: This message was deleted
25/04/26, 12:50 am - RAUSHAN Raj Tezpur: Patna me kon kon hai abhi
25/04/26, 1:37 am - Nitish Civil Kmh Tu: Mai hu
25/04/26, 1:38 am - RAUSHAN Raj Tezpur: <Media omitted>
25/04/26, 1:38 am - RAUSHAN Raj Tezpur: To aao chicken Puri khaane
25/04/26, 1:39 am - Nitish Civil Kmh Tu: Kidhar pauch gya be
25/04/26, 8:00 pm - Himanshu Kumar: Aaye the To banaya bhi sala
26/04/26, 4:27 pm - RAUSHAN Raj Tezpur: <Media omitted>
26/04/26, 4:40 pm - Amit Tu: Cctv se photo click kiye ho kya..😅
26/04/26, 5:02 pm - RAUSHAN Raj Tezpur: Live hai
29/06/26, 7:03 pm - Himanshu Kumar: Abhi Patna me koi rah raha hai kya ??
29/06/26, 9:31 pm - RAUSHAN Raj Tezpur: Samrat choudhary
29/06/26, 10:29 pm - Amit Tu: Ek baar phir se Nitish Sarkar

In [6]:
pattern = r'\d{1,2}/\d{1,2}/\d{2},\s+\d{1,2}:\d{2}\s*[ap]m\s-\s'

In [7]:
messages = re.split(pattern, data, flags=re.IGNORECASE)[1:]
messages

['Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*\n',
 'Mohit Nmh ME Tu created group "Apne Group 😎"\n',
 'You were added\n',
 'RAUSHAN Raj Tezpur: Happy Birthday to you 🎉🥳🥳🥳@\u2068Himanshu Kumar\u2069\n',
 'Shwetank Tezpur: Happy birthday 🎉🎂🎈 @\u2068Himanshu Kumar\u2069\n',
 'Himanshu Kumar: Thanks bhai ✨🫂🫂\n',
 'Himanshu Kumar: Thanks bhai 🫂✨✨\n',
 'Utkarsh Tu: happy birthday selmon bhai ✨🥂\n',
 'Rohan Gupta EE Tu: Happy birthday  @\u2068Himanshu Kumar\u2069 bhai ✨✨\n',
 'Shourya Ece Tu: Happy Birthday  bro @\u2068Himanshu Kumar\u2069 , enjoy 🔥\n',
 'Sushil Tu: Happy birthday @\u2068Himanshu Kumar\u2069\n',
 'Rohit Singh ECE NMH TU: Happy birthday @\u2068Himanshu Kumar\u2069 🎂🎉🎁 Party toh banta hai Bhai\n',
 'Rupesh (CSE) Tmh Tu: Happy Birthday @\u2068Himanshu Kumar\u2069   \nVikas bol rha tha Himanshu ke shadi ka baat chl rha hai 😃 .\n',
 'Rupesh (CSE) Tmh Tu: Happy Marriage in Advance 🥳🥳\n',
 'Somesh ECE Kmh Tu: Happy Birthday 🎉🎈🎂🎉@\u2068Himanshu Kumar\u2069\n',
 'Robin ranjan Civil Nmh Tu: Happy Birthday @\u2068Himanshu Kumar\u2069  bhai 🥳🥳🥳\n',
 'Himanshu Kumar: Thanks bhai log 🫂🥹✨ wish karne ke liyw\n',
 'Himanshu Kumar: Abhi hostel me hote ham log to kya maja karte gand faar\n',
 'Rohit Singh ECE NMH TU: Tera gand farte bhai aur kya karte\n',
 'Himanshu Kumar: 🤣🤣\n',
 'Prashun Tu: Yhi sala fartaa\n',
 'Amit Tu: Happy birthday @\u2068Himanshu Kumar\u2069 🎂🍌🍌🍒🍒\n',
 'Prashun Tu: Happy Birthday @\u2068Himanshu Kumar\u2069 brother 💦💦🎂🥳\n',
 'Vìvèk Tezpur Cse: Happy birthday @\u2068Himanshu Kumar\u2069 🍾🍾\n',
 'Amit Tu: Ye banana ko upper or apple ko niche kaise kr skte hai 🍌🍒\n',
 'Shwetank Tezpur: 🍒\n🍌\n',
 'Shwetank Tezpur: Ye lo\n',
 'Amit Tu: Ulta kro 😅\n',
 'Shwetank Tezpur: 🍌\n🍒\n',
 'Shwetank Tezpur: 🫡\n',
 'Himanshu Kumar: Thanks bhailog 🙏😊🫂✨\n',
 'Ayush Ranjan Tezpur Civil: Happy birthday 🎂 🥳 🎉 🎈 jii @\u2068Himanshu Kumar\u2069\n',
 'Himanshu Kumar: Thank u neta jii 🫂✨\n',
 'Rohan Gupta EE Tu: <Media omitted>\n',
 'Mohit Nmh ME Tu: This message was deleted\n',
 'Mohit Nmh ME Tu: Nhi 22\n',
 'Rohan Gupta EE Tu: Bhai ye sab kya ho raha hai\n',
 'Rohan Gupta EE Tu: 🫥\n',
 'Somesh ECE Kmh Tu: 2025\n',
 'Srinivash CSE Pmh Tu: 22\n',
 'Aryan Kmh Tu changed their phone number to a new number. Message or add the new number\n',
 'Srinivash CSE Pmh Tu: Happy Birthday (belated) @\u2068Suraj Tezpur\u2069\n',
 'Srinivash CSE Pmh Tu: <Media omitted>\n',
 'Rohan Gupta EE Tu: Happy birthday @\u2068Suraj Tezpur\u2069 💋💋\n',
 'Amit Tu: Happy birthday🎂🎉🎁@\u2068Suraj Tezpur\u2069\n',
 'Shwetank Tezpur: Happy birthday @\u2068Suraj Tezpur\u2069  😍 🥙 🍔 🍿 😋🐪\n',
 'Shourya Ece Tu: Happy Birthday @\u2068Suraj Tezpur\u2069  🔥✌️🎂✨️\n',
 'Utkarsh Tu: happy birthday Suraj ✨\n',
 'Suraj Tezpur: Thank you so much everyone...😀\n',
 'Himanshu Kumar: Happy birthday @\u2068Suraj Tezpur\u2069  🎂🎂🎈🎈🥳🧁\n',
 'Rupesh (CSE) Tmh Tu: Happy Birthday @\u2068Suraj Tezpur\u2069  ✨✨🥳🥳😎\n',
 'Suraj Tezpur: Thank you himanshu and rupesh 🙂\n',
 'Srinivash CSE Pmh Tu: Caution money agaya kya sabka ?\n',
 'Nitish Civil Kmh Tu: Nhi <This message was edited>\n',
 'Somesh ECE Kmh Tu: Happy Birthday 🎂🎉🎂🎂🎉🎈🎁🎉🎉🎂 @\u2068RAUSHAN Raj Tezpur\u2069\n',
 'Rohan Gupta EE Tu: Happy birthday @\u2068RAUSHAN Raj Tezpur\u2069 ✨✨\n',
 'RAUSHAN Raj Tezpur: Thank you very much\n',
 'Md Imran Ee Tmh Tu: Happy new year🎉\nBhai log ✨\n',
 'RAUSHAN Raj Tezpur: <Media omitted>\n',
 'Himanshu Kumar: Happy new year brothers ✨🫂💫🎉\n',
 'Shwetank Tezpur: Happpy New Year Bhailogwaa 🎊🎊🎊🎆\n',
 'Rohit Singh ECE NMH TU: Happy New year Everyone 🎇🎆\n',
 'Amit Tu: Happy birthday to 2026 🥳\n',
 'RAUSHAN Raj Tezpur: <Media omitted>\n',
 'RAUSHAN Raj Tezpur: POLL:\nConvocation me jayenge\nOPTION: Yes (10 votes)\nOPTION: Not sure (6 votes)\n\n',
 'Rupesh (CSE) Tmh Tu: late bta rhe hai ye log, mujhe lga ki summer vacations me hoga\n',
 'RAUSHAN Raj Tezpur: Sushil aa rha hai\n',
 'Amit Tu: This message was deleted\n',
 'Srinivash CSE Pmh Tu: 23 ho convocation h, to 24 to kisi ko rahne dega university me ?\n',
 'RAUSHAN Raj Tezpur: Ha\n',
 'Amit Tu: Raushan scooty kb bechega\n',
 'RAUSHAN Raj Tezpur: Bech diye hai\n',
 'RAUSHAN Raj Tezpur: Already\n',
 'Amit Tu: Convo me kaun aa rha h Bada aadmi\n',
 'Amit Tu: Degree dene\n',
 'RAUSHAN Raj Tezpur: Pijush chacha\n',
 'Amit Tu: Panauti\n',
 'Suraj Tezpur: trevellung peln kay hia tomlug ka?\n',
 'Suraj Tezpur: 24 ku bapus jaoge na?\n',
 'Amit Tu: Depend kaun kaha h Or kitna time spent krna chahta h dost me sath\n',
 'Suraj Tezpur: ha ysi ku to plan kehte hai wrna baki sb moh maia h\n',
 'RAUSHAN Raj Tezpur: Hyderabad se biryani lete aana\n',
 'Mohit Nmh ME Tu: Kab tak pahunchna hai college\n',
 'Suraj Tezpur: aap kahan h\n',
 'Amit Tu: Aap... Mtlb?\n',
 'RAUSHAN Raj Tezpur: Aapke dil me\n',
 'Amit Tu: 😂😂🍌\n',
 'RAUSHAN Raj Tezpur: Tumhara dil ka structure thora casual hai\n',
 'Mohit Nmh ME Tu: 😘\n',
 'Amit Tu: 😂😂\n',
 'Suraj Tezpur: arey apka job location?\n',
 'RAUSHAN Raj Tezpur: Haryana\n',
 'Suraj Tezpur: 😟\n',
 'RAUSHAN Raj Tezpur: Tha\n',
 'RAUSHAN Raj Tezpur: Thailand chalna hai\n',
 'Amit Tu: Mujhe bhi jana h... Jaoge to bolna <This message was edited>\n',
 'RAUSHAN Raj Tezpur: Chailand*\n',
 'RAUSHAN Raj Tezpur: https://www.linkedin.com/posts/drvijayendersingh_upspcbrecruitment-upspcbjobs-aeeupspcb-activity-7433347188547805184-V994?utm_source=li_share&utm_content=feedcontent&utm_medium=g_mb_web&utm_campaign=copy\n',
 'Amit Tu: @\u2068Mithun Tezpur Ee Tu\u2069 kaha ho bhai?\n',
 'RAUSHAN Raj Tezpur: Somesh ke dil me\n',
 'Amit Tu: Somesh ashik hai ya Somesh ka ashik h\n',
 'Mithun Tezpur Ee Tu: @\u2068RAUSHAN Raj Tezpur\u2069 @\u2068Amit Tu\u2069 ja raha h ki nhi convocation m\n',
 'RAUSHAN Raj Tezpur: Ha\n',
 'Amit Tu: Ha .. Kb aa rha h?\n',
 'Mithun Tezpur Ee Tu: 21\n',
 'Amit Tu: Kaha?\n',
 'Mithun Tezpur Ee Tu: This message was deleted\n',
 'Mithun Tezpur Ee Tu: Convoc\n',
 'Amit Tu: Kb se kb ka stay dega wo log?\n',
 'Mithun Tezpur Ee Tu: Relax abhi bahut din h apne batayega\n',
 'Rohan Gupta EE Tu: Stay nahi dega shyd\n',
 'Amit Tu: Kyu?\n',
 'Rohan Gupta EE Tu: Jagha kaha hai\n',
 'Mithun Tezpur Ee Tu: Bihu hoga sayad uss samay m\n',
 'Nitish Civil Kmh Tu: Tm krega na?\n',
 'Mithun Tezpur Ee Tu: @\u2068Nitish Civil Kmh Tu\u2069 ke room m jagah h\n',
 'Mithun Tezpur Ee Tu: @\u2068Rohan Gupta EE Tu\u2069\n',
 'Nitish Civil Kmh Tu: Haa ekdum aao to pahle tm\n',
 'Nitish Civil Kmh Tu: Bs POL dance kr dena <This message was edited>\n',
 'Mithun Tezpur Ee Tu: Karwayenge\n',
 'Nitish Civil Kmh Tu: Aa pahle tm\n',
 'Amit Tu: @\u2068Nitish Civil Kmh Tu\u2069  kya haal chaal hai\n',
 'Nitish Civil Kmh Tu: Kuttu paratha\n',
 'RAUSHAN Raj Tezpur: <Media omitted>\n',
 'RAUSHAN Raj Tezpur: @\u2068Vikash Ece PMH Tu\u2069 @\u2068Himanshu Kumar\u2069\n',
 'RAUSHAN Raj Tezpur: @all\n',
 'Mohit Nmh ME Tu: Ye to alag hi level ka banda hai\n',
 'Amit Tu: Ha dulha h 😎😊\n',
 'Prashun Tu: Bahinchod\n',
 'Mohit Nmh ME Tu: <Media omitted>\n',
 'Amit Tu: Bhai fielding se bachna 😅\n',
 'Prashun Tu: Dahej liya h ab fielding me koi nhi h sala dhouda kr pelega <This message was edited>\n',
 'Prashun Tu: Fielding to bs ek aadmi hi set krta tha @\u2068Robin ranjan Civil Nmh Tu\u2069\n',
 'Amit Tu: Bhai gadi ka licence hai n 😅\n',
 'Amit Tu: Ya Robin ke paas h 😂\n',
 'Srinivash CSE Pmh Tu: Sadi ho rahi h dono ki\n',
 'RAUSHAN Raj Tezpur: Per chhauri kon h\n',
 'Srinivash CSE Pmh Tu: Ye log apas me discuss kar lega, hame kya😅\n',
 'RAUSHAN Raj Tezpur: <Media omitted>\n',
 'RAUSHAN Raj Tezpur: Confirm hogaya hai\nVikash ka shaadi nhi ho rha hai\n',
 'RAUSHAN Raj Tezpur: Uske bhaiya ka shaadi hai\n',
 'Mohit Nmh ME Tu: Hm\n',
 'RAUSHAN Raj Tezpur: https://docs.google.com/forms/d/e/1FAIpQLSfxEgfhJSv48YrJnfMRUPt5pkfA1YVhKw1GllTHmQAvTAC_nA/viewform\n',
 'RAUSHAN Raj Tezpur: Sab bhar do\n',
 'RAUSHAN Raj Tezpur: Jo Jo nhi bhara hai\n',
 'RAUSHAN Raj Tezpur: Aaj last date hai\n',
 'RAUSHAN Raj Tezpur: Kon kon ticket kaant liya hai tu jaane ka\n',
 'Kush Kumar Tu: Tatkal me Dekha jaayega Mera\n',
 'RAUSHAN Raj Tezpur: <Media omitted>\n',
 'Sushil Tu: Tum zinda hai abhi tk\n',
 'RAUSHAN Raj Tezpur: Tum kya chhahte ho\n',
 'Rohan Gupta EE Tu: <Media omitted>\n',
 'Rohan Gupta EE Tu: Maderchod sale\n',
 'RAUSHAN Raj Tezpur: <Media omitted>\n',
 'RAUSHAN Raj Tezpur: Larchat administration\n',
 'RAUSHAN Raj Tezpur: Election pe blame daal diya\n',
 'Suraj Tezpur: Amazon prime h kisi k pass?@\u2068RAUSHAN Raj Tezpur\u2069\n',
 'Suraj Tezpur: ek order Krna tha bs\n',
 'RAUSHAN Raj Tezpur: Abhi to nhi hai 😔\n',
 "Suraj Tezpur: it's ok luv u😘\n",
 'Nitish Civil Kmh Tu: Happy convocation 😊\n',
 'Nitish Civil Kmh Tu: <Media omitted>\n',
 'Nitish Civil Kmh Tu: <Media omitted>\n',
 'Amit Tu: Kya mila?\n',
 'Himanshu Kumar: <Media omitted>\n',
 'Nitish Civil Kmh Tu: 🤏🏻\n',
 'Amit Tu: This message was deleted\n',
 'RAUSHAN Raj Tezpur: Patna me kon kon hai abhi\n',
 'Nitish Civil Kmh Tu: Mai hu\n',
 'RAUSHAN Raj Tezpur: <Media omitted>\n',
 'RAUSHAN Raj Tezpur: To aao chicken Puri khaane\n',
 'Nitish Civil Kmh Tu: Kidhar pauch gya be\n',
 'Himanshu Kumar: Aaye the To banaya bhi sala\n',
 'RAUSHAN Raj Tezpur: <Media omitted>\n',
 'Amit Tu: Cctv se photo click kiye ho kya..😅\n',
 'RAUSHAN Raj Tezpur: Live hai\n',
 'Himanshu Kumar: Abhi Patna me koi rah raha hai kya ??\n',
 'RAUSHAN Raj Tezpur: Samrat choudhary\n',
 'Amit Tu: Ek baar phir se Nitish Sarkar\n']

In [8]:
import re

messages = [
    re.sub(r'[\u2066-\u2069]', '', msg).replace('@', ' ').strip()
    for msg in messages
]

In [9]:
messages

['Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*',
 'Mohit Nmh ME Tu created group "Apne Group 😎"',
 'You were added',
 'RAUSHAN Raj Tezpur: Happy Birthday to you 🎉🥳🥳🥳 Himanshu Kumar',
 'Shwetank Tezpur: Happy birthday 🎉🎂🎈  Himanshu Kumar',
 'Himanshu Kumar: Thanks bhai ✨🫂🫂',
 'Himanshu Kumar: Thanks bhai 🫂✨✨',
 'Utkarsh Tu: happy birthday selmon bhai ✨🥂',
 'Rohan Gupta EE Tu: Happy birthday   Himanshu Kumar bhai ✨✨',
 'Shourya Ece Tu: Happy Birthday  bro  Himanshu Kumar , enjoy 🔥',
 'Sushil Tu: Happy birthday  Himanshu Kumar',
 'Rohit Singh ECE NMH TU: Happy birthday  Himanshu Kumar 🎂🎉🎁 Party toh banta hai Bhai',
 'Rupesh (CSE) Tmh Tu: Happy Birthday  Himanshu Kumar   \nVikas bol rha tha Himanshu ke shadi ka baat chl rha hai 😃 .',
 'Rupesh (CSE) Tmh Tu: Happy Marriage in Advance 🥳🥳',
 'Somesh ECE Kmh Tu: Happy Birthday 🎉🎈🎂🎉 Himanshu Kumar',
 'Robin ranjan Civil Nmh Tu: Happy Birthday  Himanshu Kumar  bhai 🥳🥳🥳',
 'Himanshu Kumar: Thanks bhai log 🫂🥹✨ wish karne ke liyw',
 'Himanshu Kumar: Abhi hostel me hote ham log to kya maja karte gand faar',
 'Rohit Singh ECE NMH TU: Tera gand farte bhai aur kya karte',
 'Himanshu Kumar: 🤣🤣',
 'Prashun Tu: Yhi sala fartaa',
 'Amit Tu: Happy birthday  Himanshu Kumar 🎂🍌🍌🍒🍒',
 'Prashun Tu: Happy Birthday  Himanshu Kumar brother 💦💦🎂🥳',
 'Vìvèk Tezpur Cse: Happy birthday  Himanshu Kumar 🍾🍾',
 'Amit Tu: Ye banana ko upper or apple ko niche kaise kr skte hai 🍌🍒',
 'Shwetank Tezpur: 🍒\n🍌',
 'Shwetank Tezpur: Ye lo',
 'Amit Tu: Ulta kro 😅',
 'Shwetank Tezpur: 🍌\n🍒',
 'Shwetank Tezpur: 🫡',
 'Himanshu Kumar: Thanks bhailog 🙏😊🫂✨',
 'Ayush Ranjan Tezpur Civil: Happy birthday 🎂 🥳 🎉 🎈 jii  Himanshu Kumar',
 'Himanshu Kumar: Thank u neta jii 🫂✨',
 'Rohan Gupta EE Tu: <Media omitted>',
 'Mohit Nmh ME Tu: This message was deleted',
 'Mohit Nmh ME Tu: Nhi 22',
 'Rohan Gupta EE Tu: Bhai ye sab kya ho raha hai',
 'Rohan Gupta EE Tu: 🫥',
 'Somesh ECE Kmh Tu: 2025',
 'Srinivash CSE Pmh Tu: 22',
 'Aryan Kmh Tu changed their phone number to a new number. Message or add the new number',
 'Srinivash CSE Pmh Tu: Happy Birthday (belated)  Suraj Tezpur',
 'Srinivash CSE Pmh Tu: <Media omitted>',
 'Rohan Gupta EE Tu: Happy birthday  Suraj Tezpur 💋💋',
 'Amit Tu: Happy birthday🎂🎉🎁 Suraj Tezpur',
 'Shwetank Tezpur: Happy birthday  Suraj Tezpur  😍 🥙 🍔 🍿 😋🐪',
 'Shourya Ece Tu: Happy Birthday  Suraj Tezpur  🔥✌️🎂✨️',
 'Utkarsh Tu: happy birthday Suraj ✨',
 'Suraj Tezpur: Thank you so much everyone...😀',
 'Himanshu Kumar: Happy birthday  Suraj Tezpur  🎂🎂🎈🎈🥳🧁',
 'Rupesh (CSE) Tmh Tu: Happy Birthday  Suraj Tezpur  ✨✨🥳🥳😎',
 'Suraj Tezpur: Thank you himanshu and rupesh 🙂',
 'Srinivash CSE Pmh Tu: Caution money agaya kya sabka ?',
 'Nitish Civil Kmh Tu: Nhi <This message was edited>',
 'Somesh ECE Kmh Tu: Happy Birthday 🎂🎉🎂🎂🎉🎈🎁🎉🎉🎂  RAUSHAN Raj Tezpur',
 'Rohan Gupta EE Tu: Happy birthday  RAUSHAN Raj Tezpur ✨✨',
 'RAUSHAN Raj Tezpur: Thank you very much',
 'Md Imran Ee Tmh Tu: Happy new year🎉\nBhai log ✨',
 'RAUSHAN Raj Tezpur: <Media omitted>',
 'Himanshu Kumar: Happy new year brothers ✨🫂💫🎉',
 'Shwetank Tezpur: Happpy New Year Bhailogwaa 🎊🎊🎊🎆',
 'Rohit Singh ECE NMH TU: Happy New year Everyone 🎇🎆',
 'Amit Tu: Happy birthday to 2026 🥳',
 'RAUSHAN Raj Tezpur: <Media omitted>',
 'RAUSHAN Raj Tezpur: POLL:\nConvocation me jayenge\nOPTION: Yes (10 votes)\nOPTION: Not sure (6 votes)',
 'Rupesh (CSE) Tmh Tu: late bta rhe hai ye log, mujhe lga ki summer vacations me hoga',
 'RAUSHAN Raj Tezpur: Sushil aa rha hai',
 'Amit Tu: This message was deleted',
 'Srinivash CSE Pmh Tu: 23 ho convocation h, to 24 to kisi ko rahne dega university me ?',
 'RAUSHAN Raj Tezpur: Ha',
 'Amit Tu: Raushan scooty kb bechega',
 'RAUSHAN Raj Tezpur: Bech diye hai',
 'RAUSHAN Raj Tezpur: Already',
 'Amit Tu: Convo me kaun aa rha h Bada aadmi',
 'Amit Tu: Degree dene',
 'RAUSHAN Raj Tezpur: Pijush chacha',
 'Amit Tu: Panauti',
 'Suraj Tezpur: trevellung peln kay hia tomlug ka?',
 'Suraj Tezpur: 24 ku bapus jaoge na?',
 'Amit Tu: Depend kaun kaha h Or kitna time spent krna chahta h dost me sath',
 'Suraj Tezpur: ha ysi ku to plan kehte hai wrna baki sb moh maia h',
 'RAUSHAN Raj Tezpur: Hyderabad se biryani lete aana',
 'Mohit Nmh ME Tu: Kab tak pahunchna hai college',
 'Suraj Tezpur: aap kahan h',
 'Amit Tu: Aap... Mtlb?',
 'RAUSHAN Raj Tezpur: Aapke dil me',
 'Amit Tu: 😂😂🍌',
 'RAUSHAN Raj Tezpur: Tumhara dil ka structure thora casual hai',
 'Mohit Nmh ME Tu: 😘',
 'Amit Tu: 😂😂',
 'Suraj Tezpur: arey apka job location?',
 'RAUSHAN Raj Tezpur: Haryana',
 'Suraj Tezpur: 😟',
 'RAUSHAN Raj Tezpur: Tha',
 'RAUSHAN Raj Tezpur: Thailand chalna hai',
 'Amit Tu: Mujhe bhi jana h... Jaoge to bolna <This message was edited>',
 'RAUSHAN Raj Tezpur: Chailand*',
 'RAUSHAN Raj Tezpur: https://www.linkedin.com/posts/drvijayendersingh_upspcbrecruitment-upspcbjobs-aeeupspcb-activity-7433347188547805184-V994?utm_source=li_share&utm_content=feedcontent&utm_medium=g_mb_web&utm_campaign=copy',
 'Amit Tu:  Mithun Tezpur Ee Tu kaha ho bhai?',
 'RAUSHAN Raj Tezpur: Somesh ke dil me',
 'Amit Tu: Somesh ashik hai ya Somesh ka ashik h',
 'Mithun Tezpur Ee Tu:  RAUSHAN Raj Tezpur  Amit Tu ja raha h ki nhi convocation m',
 'RAUSHAN Raj Tezpur: Ha',
 'Amit Tu: Ha .. Kb aa rha h?',
 'Mithun Tezpur Ee Tu: 21',
 'Amit Tu: Kaha?',
 'Mithun Tezpur Ee Tu: This message was deleted',
 'Mithun Tezpur Ee Tu: Convoc',
 'Amit Tu: Kb se kb ka stay dega wo log?',
 'Mithun Tezpur Ee Tu: Relax abhi bahut din h apne batayega',
 'Rohan Gupta EE Tu: Stay nahi dega shyd',
 'Amit Tu: Kyu?',
 'Rohan Gupta EE Tu: Jagha kaha hai',
 'Mithun Tezpur Ee Tu: Bihu hoga sayad uss samay m',
 'Nitish Civil Kmh Tu: Tm krega na?',
 'Mithun Tezpur Ee Tu:  Nitish Civil Kmh Tu ke room m jagah h',
 'Mithun Tezpur Ee Tu:  Rohan Gupta EE Tu',
 'Nitish Civil Kmh Tu: Haa ekdum aao to pahle tm',
 'Nitish Civil Kmh Tu: Bs POL dance kr dena <This message was edited>',
 'Mithun Tezpur Ee Tu: Karwayenge',
 'Nitish Civil Kmh Tu: Aa pahle tm',
 'Amit Tu:  Nitish Civil Kmh Tu  kya haal chaal hai',
 'Nitish Civil Kmh Tu: Kuttu paratha',
 'RAUSHAN Raj Tezpur: <Media omitted>',
 'RAUSHAN Raj Tezpur:  Vikash Ece PMH Tu  Himanshu Kumar',
 'RAUSHAN Raj Tezpur:  all',
 'Mohit Nmh ME Tu: Ye to alag hi level ka banda hai',
 'Amit Tu: Ha dulha h 😎😊',
 'Prashun Tu: Bahinchod',
 'Mohit Nmh ME Tu: <Media omitted>',
 'Amit Tu: Bhai fielding se bachna 😅',
 'Prashun Tu: Dahej liya h ab fielding me koi nhi h sala dhouda kr pelega <This message was edited>',
 'Prashun Tu: Fielding to bs ek aadmi hi set krta tha  Robin ranjan Civil Nmh Tu',
 'Amit Tu: Bhai gadi ka licence hai n 😅',
 'Amit Tu: Ya Robin ke paas h 😂',
 'Srinivash CSE Pmh Tu: Sadi ho rahi h dono ki',
 'RAUSHAN Raj Tezpur: Per chhauri kon h',
 'Srinivash CSE Pmh Tu: Ye log apas me discuss kar lega, hame kya😅',
 'RAUSHAN Raj Tezpur: <Media omitted>',
 'RAUSHAN Raj Tezpur: Confirm hogaya hai\nVikash ka shaadi nhi ho rha hai',
 'RAUSHAN Raj Tezpur: Uske bhaiya ka shaadi hai',
 'Mohit Nmh ME Tu: Hm',
 'RAUSHAN Raj Tezpur: https://docs.google.com/forms/d/e/1FAIpQLSfxEgfhJSv48YrJnfMRUPt5pkfA1YVhKw1GllTHmQAvTAC_nA/viewform',
 'RAUSHAN Raj Tezpur: Sab bhar do',
 'RAUSHAN Raj Tezpur: Jo Jo nhi bhara hai',
 'RAUSHAN Raj Tezpur: Aaj last date hai',
 'RAUSHAN Raj Tezpur: Kon kon ticket kaant liya hai tu jaane ka',
 'Kush Kumar Tu: Tatkal me Dekha jaayega Mera',
 'RAUSHAN Raj Tezpur: <Media omitted>',
 'Sushil Tu: Tum zinda hai abhi tk',
 'RAUSHAN Raj Tezpur: Tum kya chhahte ho',
 'Rohan Gupta EE Tu: <Media omitted>',
 'Rohan Gupta EE Tu: Maderchod sale',
 'RAUSHAN Raj Tezpur: <Media omitted>',
 'RAUSHAN Raj Tezpur: Larchat administration',
 'RAUSHAN Raj Tezpur: Election pe blame daal diya',
 'Suraj Tezpur: Amazon prime h kisi k pass? RAUSHAN Raj Tezpur',
 'Suraj Tezpur: ek order Krna tha bs',
 'RAUSHAN Raj Tezpur: Abhi to nhi hai 😔',
 "Suraj Tezpur: it's ok luv u😘",
 'Nitish Civil Kmh Tu: Happy convocation 😊',
 'Nitish Civil Kmh Tu: <Media omitted>',
 'Nitish Civil Kmh Tu: <Media omitted>',
 'Amit Tu: Kya mila?',
 'Himanshu Kumar: <Media omitted>',
 'Nitish Civil Kmh Tu: 🤏🏻',
 'Amit Tu: This message was deleted',
 'RAUSHAN Raj Tezpur: Patna me kon kon hai abhi',
 'Nitish Civil Kmh Tu: Mai hu',
 'RAUSHAN Raj Tezpur: <Media omitted>',
 'RAUSHAN Raj Tezpur: To aao chicken Puri khaane',
 'Nitish Civil Kmh Tu: Kidhar pauch gya be',
 'Himanshu Kumar: Aaye the To banaya bhi sala',
 'RAUSHAN Raj Tezpur: <Media omitted>',
 'Amit Tu: Cctv se photo click kiye ho kya..😅',
 'RAUSHAN Raj Tezpur: Live hai',
 'Himanshu Kumar: Abhi Patna me koi rah raha hai kya ??',
 'RAUSHAN Raj Tezpur: Samrat choudhary',
 'Amit Tu: Ek baar phir se Nitish Sarkar']

In [10]:
dates = re.findall(pattern, data)
dates

['09/08/25, 10:26\u202fpm - ',
 '17/10/22, 1:56\u202fam - ',
 '17/10/22, 1:56\u202fam - ',
 '16/08/25, 2:19\u202fpm - ',
 '16/08/25, 2:27\u202fpm - ',
 '16/08/25, 6:04\u202fpm - ',
 '16/08/25, 6:04\u202fpm - ',
 '16/08/25, 6:15\u202fpm - ',
 '16/08/25, 6:19\u202fpm - ',
 '16/08/25, 7:01\u202fpm - ',
 '16/08/25, 7:16\u202fpm - ',
 '16/08/25, 7:26\u202fpm - ',
 '16/08/25, 8:09\u202fpm - ',
 '16/08/25, 8:09\u202fpm - ',
 '16/08/25, 8:15\u202fpm - ',
 '16/08/25, 8:45\u202fpm - ',
 '16/08/25, 9:05\u202fpm - ',
 '16/08/25, 9:06\u202fpm - ',
 '16/08/25, 9:07\u202fpm - ',
 '16/08/25, 9:08\u202fpm - ',
 '16/08/25, 9:19\u202fpm - ',
 '16/08/25, 9:20\u202fpm - ',
 '16/08/25, 9:21\u202fpm - ',
 '16/08/25, 9:22\u202fpm - ',
 '16/08/25, 9:22\u202fpm - ',
 '16/08/25, 9:31\u202fpm - ',
 '16/08/25, 9:31\u202fpm - ',
 '16/08/25, 9:34\u202fpm - ',
 '16/08/25, 9:35\u202fpm - ',
 '16/08/25, 9:35\u202fpm - ',
 '16/08/25, 10:08\u202fpm - ',
 '16/08/25, 10:54\u202fpm - ',
 '16/08/25, 11:44\u202fpm - ',
 '20/08/25, 1:12\u202fpm - ',
 '20/08/25, 1:12\u202fpm - ',
 '20/08/25, 1:12\u202fpm - ',
 '20/08/25, 1:17\u202fpm - ',
 '20/08/25, 1:17\u202fpm - ',
 '20/08/25, 1:29\u202fpm - ',
 '20/08/25, 3:30\u202fpm - ',
 '23/08/25, 10:43\u202fpm - ',
 '30/09/25, 5:51\u202fpm - ',
 '30/09/25, 5:51\u202fpm - ',
 '30/09/25, 5:55\u202fpm - ',
 '30/09/25, 6:00\u202fpm - ',
 '30/09/25, 6:36\u202fpm - ',
 '30/09/25, 7:08\u202fpm - ',
 '30/09/25, 11:12\u202fpm - ',
 '30/09/25, 11:21\u202fpm - ',
 '30/09/25, 11:27\u202fpm - ',
 '01/10/25, 8:47\u202fam - ',
 '01/10/25, 10:32\u202fpm - ',
 '04/11/25, 9:59\u202fpm - ',
 '05/11/25, 12:04\u202fam - ',
 '20/11/25, 9:11\u202fpm - ',
 '20/11/25, 9:26\u202fpm - ',
 '20/11/25, 9:49\u202fpm - ',
 '01/01/26, 10:37\u202fam - ',
 '01/01/26, 10:52\u202fam - ',
 '01/01/26, 11:46\u202fam - ',
 '01/01/26, 11:47\u202fam - ',
 '01/01/26, 12:38\u202fpm - ',
 '01/01/26, 1:12\u202fpm - ',
 '27/02/26, 11:54\u202fam - ',
 '27/02/26, 12:12\u202fpm - ',
 '28/02/26, 9:05\u202fam - ',
 '28/02/26, 10:18\u202fam - ',
 '28/02/26, 10:28\u202fam - ',
 '28/02/26, 10:36\u202fam - ',
 '28/02/26, 11:00\u202fam - ',
 '28/02/26, 11:01\u202fam - ',
 '28/02/26, 11:01\u202fam - ',
 '28/02/26, 11:01\u202fam - ',
 '28/02/26, 11:02\u202fam - ',
 '28/02/26, 11:03\u202fam - ',
 '28/02/26, 11:03\u202fam - ',
 '28/02/26, 11:04\u202fam - ',
 '28/02/26, 11:29\u202fam - ',
 '28/02/26, 11:29\u202fam - ',
 '28/02/26, 11:45\u202fam - ',
 '28/02/26, 12:08\u202fpm - ',
 '28/02/26, 12:15\u202fpm - ',
 '28/02/26, 12:16\u202fpm - ',
 '28/02/26, 12:17\u202fpm - ',
 '28/02/26, 12:17\u202fpm - ',
 '28/02/26, 12:17\u202fpm - ',
 '28/02/26, 12:17\u202fpm - ',
 '28/02/26, 12:17\u202fpm - ',
 '28/02/26, 12:18\u202fpm - ',
 '28/02/26, 12:18\u202fpm - ',
 '28/02/26, 12:18\u202fpm - ',
 '28/02/26, 12:18\u202fpm - ',
 '28/02/26, 12:19\u202fpm - ',
 '28/02/26, 12:21\u202fpm - ',
 '28/02/26, 12:21\u202fpm - ',
 '28/02/26, 12:22\u202fpm - ',
 '28/02/26, 12:22\u202fpm - ',
 '28/02/26, 12:22\u202fpm - ',
 '28/02/26, 12:23\u202fpm - ',
 '28/02/26, 12:23\u202fpm - ',
 '28/02/26, 12:25\u202fpm - ',
 '28/02/26, 3:59\u202fpm - ',
 '28/02/26, 4:00\u202fpm - ',
 '28/02/26, 4:58\u202fpm - ',
 '28/02/26, 5:05\u202fpm - ',
 '28/02/26, 5:08\u202fpm - ',
 '28/02/26, 5:09\u202fpm - ',
 '28/02/26, 5:09\u202fpm - ',
 '28/02/26, 5:09\u202fpm - ',
 '28/02/26, 5:10\u202fpm - ',
 '28/02/26, 5:10\u202fpm - ',
 '28/02/26, 5:10\u202fpm - ',
 '28/02/26, 5:12\u202fpm - ',
 '28/02/26, 5:12\u202fpm - ',
 '28/02/26, 5:31\u202fpm - ',
 '28/02/26, 5:33\u202fpm - ',
 '28/02/26, 5:33\u202fpm - ',
 '28/02/26, 5:34\u202fpm - ',
 '28/02/26, 5:34\u202fpm - ',
 '28/02/26, 5:34\u202fpm - ',
 '28/02/26, 5:35\u202fpm - ',
 '28/02/26, 5:36\u202fpm - ',
 '28/02/26, 5:45\u202fpm - ',
 '09/03/26, 5:18\u202fpm - ',
 '09/03/26, 5:18\u202fpm - ',
 '09/03/26, 5:18\u202fpm - ',
 '09/03/26, 5:23\u202fpm - ',
 '09/03/26, 5:29\u202fpm - ',
 '09/03/26, 5:39\u202fpm - ',
 '09/03/26, 5:40\u202fpm - ',
 '09/03/26, 5:41\u202fpm - ',
 '09/03/26, 5:42\u202fpm - ',
 '09/03/26, 5:45\u202fpm - ',
 '09/03/26, 5:47\u202fpm - ',
 '09/03/26, 5:48\u202fpm - ',
 '09/03/26, 6:24\u202fpm - ',
 '09/03/26, 6:26\u202fpm - ',
 '09/03/26, 6:26\u202fpm - ',
 '09/03/26, 6:46\u202fpm - ',
 '10/03/26, 11:23\u202fam - ',
 '10/03/26, 11:23\u202fam - ',
 '10/03/26, 11:23\u202fam - ',
 '11/03/26, 9:53\u202fpm - ',
 '11/03/26, 9:53\u202fpm - ',
 '11/03/26, 9:53\u202fpm - ',
 '15/03/26, 1:42\u202fpm - ',
 '16/03/26, 4:45\u202fpm - ',
 '16/03/26, 4:46\u202fpm - ',
 '16/03/26, 4:54\u202fpm - ',
 '16/03/26, 5:18\u202fpm - ',
 '16/03/26, 5:23\u202fpm - ',
 '16/03/26, 6:06\u202fpm - ',
 '16/03/26, 6:06\u202fpm - ',
 '16/03/26, 6:08\u202fpm - ',
 '16/03/26, 6:08\u202fpm - ',
 '16/03/26, 6:08\u202fpm - ',
 '17/03/26, 3:06\u202fpm - ',
 '17/03/26, 3:06\u202fpm - ',
 '17/03/26, 4:50\u202fpm - ',
 '17/03/26, 7:48\u202fpm - ',
 '23/03/26, 11:32\u202fam - ',
 '23/03/26, 11:27\u202fpm - ',
 '23/03/26, 11:27\u202fpm - ',
 '23/03/26, 11:46\u202fpm - ',
 '24/03/26, 12:10\u202fam - ',
 '24/03/26, 12:34\u202fam - ',
 '25/03/26, 11:28\u202fam - ',
 '25/04/26, 12:50\u202fam - ',
 '25/04/26, 1:37\u202fam - ',
 '25/04/26, 1:38\u202fam - ',
 '25/04/26, 1:38\u202fam - ',
 '25/04/26, 1:39\u202fam - ',
 '25/04/26, 8:00\u202fpm - ',
 '26/04/26, 4:27\u202fpm - ',
 '26/04/26, 4:40\u202fpm - ',
 '26/04/26, 5:02\u202fpm - ',
 '29/06/26, 7:03\u202fpm - ',
 '29/06/26, 9:31\u202fpm - ',
 '29/06/26, 10:29\u202fpm - ']

In [11]:
dates = [d.replace('\u202f', ' ') for d in dates]

In [12]:
dates

['09/08/25, 10:26 pm - ',
 '17/10/22, 1:56 am - ',
 '17/10/22, 1:56 am - ',
 '16/08/25, 2:19 pm - ',
 '16/08/25, 2:27 pm - ',
 '16/08/25, 6:04 pm - ',
 '16/08/25, 6:04 pm - ',
 '16/08/25, 6:15 pm - ',
 '16/08/25, 6:19 pm - ',
 '16/08/25, 7:01 pm - ',
 '16/08/25, 7:16 pm - ',
 '16/08/25, 7:26 pm - ',
 '16/08/25, 8:09 pm - ',
 '16/08/25, 8:09 pm - ',
 '16/08/25, 8:15 pm - ',
 '16/08/25, 8:45 pm - ',
 '16/08/25, 9:05 pm - ',
 '16/08/25, 9:06 pm - ',
 '16/08/25, 9:07 pm - ',
 '16/08/25, 9:08 pm - ',
 '16/08/25, 9:19 pm - ',
 '16/08/25, 9:20 pm - ',
 '16/08/25, 9:21 pm - ',
 '16/08/25, 9:22 pm - ',
 '16/08/25, 9:22 pm - ',
 '16/08/25, 9:31 pm - ',
 '16/08/25, 9:31 pm - ',
 '16/08/25, 9:34 pm - ',
 '16/08/25, 9:35 pm - ',
 '16/08/25, 9:35 pm - ',
 '16/08/25, 10:08 pm - ',
 '16/08/25, 10:54 pm - ',
 '16/08/25, 11:44 pm - ',
 '20/08/25, 1:12 pm - ',
 '20/08/25, 1:12 pm - ',
 '20/08/25, 1:12 pm - ',
 '20/08/25, 1:17 pm - ',
 '20/08/25, 1:17 pm - ',
 '20/08/25, 1:29 pm - ',
 '20/08/25, 3:30 pm - ',
 '23/08/25, 10:43 pm - ',
 '30/09/25, 5:51 pm - ',
 '30/09/25, 5:51 pm - ',
 '30/09/25, 5:55 pm - ',
 '30/09/25, 6:00 pm - ',
 '30/09/25, 6:36 pm - ',
 '30/09/25, 7:08 pm - ',
 '30/09/25, 11:12 pm - ',
 '30/09/25, 11:21 pm - ',
 '30/09/25, 11:27 pm - ',
 '01/10/25, 8:47 am - ',
 '01/10/25, 10:32 pm - ',
 '04/11/25, 9:59 pm - ',
 '05/11/25, 12:04 am - ',
 '20/11/25, 9:11 pm - ',
 '20/11/25, 9:26 pm - ',
 '20/11/25, 9:49 pm - ',
 '01/01/26, 10:37 am - ',
 '01/01/26, 10:52 am - ',
 '01/01/26, 11:46 am - ',
 '01/01/26, 11:47 am - ',
 '01/01/26, 12:38 pm - ',
 '01/01/26, 1:12 pm - ',
 '27/02/26, 11:54 am - ',
 '27/02/26, 12:12 pm - ',
 '28/02/26, 9:05 am - ',
 '28/02/26, 10:18 am - ',
 '28/02/26, 10:28 am - ',
 '28/02/26, 10:36 am - ',
 '28/02/26, 11:00 am - ',
 '28/02/26, 11:01 am - ',
 '28/02/26, 11:01 am - ',
 '28/02/26, 11:01 am - ',
 '28/02/26, 11:02 am - ',
 '28/02/26, 11:03 am - ',
 '28/02/26, 11:03 am - ',
 '28/02/26, 11:04 am - ',
 '28/02/26, 11:29 am - ',
 '28/02/26, 11:29 am - ',
 '28/02/26, 11:45 am - ',
 '28/02/26, 12:08 pm - ',
 '28/02/26, 12:15 pm - ',
 '28/02/26, 12:16 pm - ',
 '28/02/26, 12:17 pm - ',
 '28/02/26, 12:17 pm - ',
 '28/02/26, 12:17 pm - ',
 '28/02/26, 12:17 pm - ',
 '28/02/26, 12:17 pm - ',
 '28/02/26, 12:18 pm - ',
 '28/02/26, 12:18 pm - ',
 '28/02/26, 12:18 pm - ',
 '28/02/26, 12:18 pm - ',
 '28/02/26, 12:19 pm - ',
 '28/02/26, 12:21 pm - ',
 '28/02/26, 12:21 pm - ',
 '28/02/26, 12:22 pm - ',
 '28/02/26, 12:22 pm - ',
 '28/02/26, 12:22 pm - ',
 '28/02/26, 12:23 pm - ',
 '28/02/26, 12:23 pm - ',
 '28/02/26, 12:25 pm - ',
 '28/02/26, 3:59 pm - ',
 '28/02/26, 4:00 pm - ',
 '28/02/26, 4:58 pm - ',
 '28/02/26, 5:05 pm - ',
 '28/02/26, 5:08 pm - ',
 '28/02/26, 5:09 pm - ',
 '28/02/26, 5:09 pm - ',
 '28/02/26, 5:09 pm - ',
 '28/02/26, 5:10 pm - ',
 '28/02/26, 5:10 pm - ',
 '28/02/26, 5:10 pm - ',
 '28/02/26, 5:12 pm - ',
 '28/02/26, 5:12 pm - ',
 '28/02/26, 5:31 pm - ',
 '28/02/26, 5:33 pm - ',
 '28/02/26, 5:33 pm - ',
 '28/02/26, 5:34 pm - ',
 '28/02/26, 5:34 pm - ',
 '28/02/26, 5:34 pm - ',
 '28/02/26, 5:35 pm - ',
 '28/02/26, 5:36 pm - ',
 '28/02/26, 5:45 pm - ',
 '09/03/26, 5:18 pm - ',
 '09/03/26, 5:18 pm - ',
 '09/03/26, 5:18 pm - ',
 '09/03/26, 5:23 pm - ',
 '09/03/26, 5:29 pm - ',
 '09/03/26, 5:39 pm - ',
 '09/03/26, 5:40 pm - ',
 '09/03/26, 5:41 pm - ',
 '09/03/26, 5:42 pm - ',
 '09/03/26, 5:45 pm - ',
 '09/03/26, 5:47 pm - ',
 '09/03/26, 5:48 pm - ',
 '09/03/26, 6:24 pm - ',
 '09/03/26, 6:26 pm - ',
 '09/03/26, 6:26 pm - ',
 '09/03/26, 6:46 pm - ',
 '10/03/26, 11:23 am - ',
 '10/03/26, 11:23 am - ',
 '10/03/26, 11:23 am - ',
 '11/03/26, 9:53 pm - ',
 '11/03/26, 9:53 pm - ',
 '11/03/26, 9:53 pm - ',
 '15/03/26, 1:42 pm - ',
 '16/03/26, 4:45 pm - ',
 '16/03/26, 4:46 pm - ',
 '16/03/26, 4:54 pm - ',
 '16/03/26, 5:18 pm - ',
 '16/03/26, 5:23 pm - ',
 '16/03/26, 6:06 pm - ',
 '16/03/26, 6:06 pm - ',
 '16/03/26, 6:08 pm - ',
 '16/03/26, 6:08 pm - ',
 '16/03/26, 6:08 pm - ',
 '17/03/26, 3:06 pm - ',
 '17/03/26, 3:06 pm - ',
 '17/03/26, 4:50 pm - ',
 '17/03/26, 7:48 pm - ',
 '23/03/26, 11:32 am - ',
 '23/03/26, 11:27 pm - ',
 '23/03/26, 11:27 pm - ',
 '23/03/26, 11:46 pm - ',
 '24/03/26, 12:10 am - ',
 '24/03/26, 12:34 am - ',
 '25/03/26, 11:28 am - ',
 '25/04/26, 12:50 am - ',
 '25/04/26, 1:37 am - ',
 '25/04/26, 1:38 am - ',
 '25/04/26, 1:38 am - ',
 '25/04/26, 1:39 am - ',
 '25/04/26, 8:00 pm - ',
 '26/04/26, 4:27 pm - ',
 '26/04/26, 4:40 pm - ',
 '26/04/26, 5:02 pm - ',
 '29/06/26, 7:03 pm - ',
 '29/06/26, 9:31 pm - ',
 '29/06/26, 10:29 pm - ']

In [13]:
import pandas as pd

df = pd.DataFrame({
    'user_message': messages,
    'message_date': dates
})

# Replace Unicode narrow space with a normal space


# Convert to datetime
df['message_date'] = pd.to_datetime(
    df['message_date'],
    format='%d/%m/%y, %I:%M %p - '
)

df['date_12hr'] = df['message_date'].dt.strftime('%d/%m/%Y, %I:%M %p').str.lower()

df.rename(columns={'message_date': 'date'}, inplace=True)

df.head()

,user_message,date,date_12hr
0,Messages and calls are end-to-end encrypted. O...,2025-08-09 22:26:00,"09/08/2025, 10:26 pm"
1,"Mohit Nmh ME Tu created group ""Apne Group 😎""",2022-10-17 01:56:00,"17/10/2022, 01:56 am"
2,You were added,2022-10-17 01:56:00,"17/10/2022, 01:56 am"
3,RAUSHAN Raj Tezpur: Happy Birthday to you 🎉🥳🥳🥳...,2025-08-16 14:19:00,"16/08/2025, 02:19 pm"
4,Shwetank Tezpur: Happy birthday 🎉🎂🎈 Himanshu ...,2025-08-16 14:27:00,"16/08/2025, 02:27 pm"

In [14]:
df.shape

(179, 3)

In [15]:
users = []
messages = []

for msg in df['user_message']:
    if ': ' in msg:
        user, message = msg.split(': ', 1)  # Split only once
        users.append(user)
        messages.append(message)
    else:
        users.append('group_notification')
        messages.append(msg)

df['user'] = users
df['message'] = messages

In [16]:
df.drop(columns=['user_message'], inplace=True)

In [17]:
df.head()

,date,date_12hr,user,message
0,2025-08-09 22:26:00,"09/08/2025, 10:26 pm",group_notification,Messages and calls are end-to-end encrypted. O...
1,2022-10-17 01:56:00,"17/10/2022, 01:56 am",group_notification,"Mohit Nmh ME Tu created group ""Apne Group 😎"""
2,2022-10-17 01:56:00,"17/10/2022, 01:56 am",group_notification,You were added
3,2025-08-16 14:19:00,"16/08/2025, 02:19 pm",RAUSHAN Raj Tezpur,Happy Birthday to you 🎉🥳🥳🥳 Himanshu Kumar
4,2025-08-16 14:27:00,"16/08/2025, 02:27 pm",Shwetank Tezpur,Happy birthday 🎉🎂🎈 Himanshu Kumar

In [18]:
df["year"] = df['date'].dt.year

In [19]:
df.head()

,date,date_12hr,user,message,year
0,2025-08-09 22:26:00,"09/08/2025, 10:26 pm",group_notification,Messages and calls are end-to-end encrypted. O...,2025
1,2022-10-17 01:56:00,"17/10/2022, 01:56 am",group_notification,"Mohit Nmh ME Tu created group ""Apne Group 😎""",2022
2,2022-10-17 01:56:00,"17/10/2022, 01:56 am",group_notification,You were added,2022
3,2025-08-16 14:19:00,"16/08/2025, 02:19 pm",RAUSHAN Raj Tezpur,Happy Birthday to you 🎉🥳🥳🥳 Himanshu Kumar,2025
4,2025-08-16 14:27:00,"16/08/2025, 02:27 pm",Shwetank Tezpur,Happy birthday 🎉🎂🎈 Himanshu Kumar,2025

In [20]:
df["month"] = df["date"].dt.month_name()

In [21]:
df["day"] = df["date"].dt.day

In [22]:
df["hour"] = df["date"].dt.hour

In [23]:
df["minute"] = df["date"].dt.minute

In [24]:
df.head()

,date,date_12hr,user,message,year,month,day,hour,minute
0,2025-08-09 22:26:00,"09/08/2025, 10:26 pm",group_notification,Messages and calls are end-to-end encrypted. O...,2025,August,9,22,26
1,2022-10-17 01:56:00,"17/10/2022, 01:56 am",group_notification,"Mohit Nmh ME Tu created group ""Apne Group 😎""",2022,October,17,1,56
2,2022-10-17 01:56:00,"17/10/2022, 01:56 am",group_notification,You were added,2022,October,17,1,56
3,2025-08-16 14:19:00,"16/08/2025, 02:19 pm",RAUSHAN Raj Tezpur,Happy Birthday to you 🎉🥳🥳🥳 Himanshu Kumar,2025,August,16,14,19
4,2025-08-16 14:27:00,"16/08/2025, 02:27 pm",Shwetank Tezpur,Happy birthday 🎉🎂🎈 Himanshu Kumar,2025,August,16,14,27

In [26]:
df[df['message'] == '<Media omitted>']

,date,date_12hr,user,message,year,month,day,hour,minute
33,2025-08-20 13:12:00,"20/08/2025, 01:12 pm",Rohan Gupta EE Tu,<Media omitted>,2025,August,20,13,12
42,2025-09-30 17:51:00,"30/09/2025, 05:51 pm",Srinivash CSE Pmh Tu,<Media omitted>,2025,September,30,17,51
58,2026-01-01 10:52:00,"01/01/2026, 10:52 am",RAUSHAN Raj Tezpur,<Media omitted>,2026,January,1,10,52
63,2026-02-27 11:54:00,"27/02/2026, 11:54 am",RAUSHAN Raj Tezpur,<Media omitted>,2026,February,27,11,54
123,2026-03-09 17:18:00,"09/03/2026, 05:18 pm",RAUSHAN Raj Tezpur,<Media omitted>,2026,March,9,17,18
129,2026-03-09 17:40:00,"09/03/2026, 05:40 pm",Mohit Nmh ME Tu,<Media omitted>,2026,March,9,17,40
138,2026-03-09 18:46:00,"09/03/2026, 06:46 pm",RAUSHAN Raj Tezpur,<Media omitted>,2026,March,9,18,46
148,2026-03-16 16:54:00,"16/03/2026, 04:54 pm",RAUSHAN Raj Tezpur,<Media omitted>,2026,March,16,16,54
151,2026-03-16 18:06:00,"16/03/2026, 06:06 pm",Rohan Gupta EE Tu,<Media omitted>,2026,March,16,18,6
153,2026-03-16 18:08:00,"16/03/2026, 06:08 pm",RAUSHAN Raj Tezpur,<Media omitted>,2026,March,16,18,8
161,2026-03-23 23:27:00,"23/03/2026, 11:27 pm",Nitish Civil Kmh Tu,<Media omitted>,2026,March,23,23,27
162,2026-03-23 23:27:00,"23/03/2026, 11:27 pm",Nitish Civil Kmh Tu,<Media omitted>,2026,March,23,23,27
164,2026-03-24 00:10:00,"24/03/2026, 12:10 am",Himanshu Kumar,<Media omitted>,2026,March,24,0,10
169,2026-04-25 01:38:00,"25/04/2026, 01:38 am",RAUSHAN Raj Tezpur,<Media omitted>,2026,April,25,1,38
173,2026-04-26 16:27:00,"26/04/2026, 04:27 pm",RAUSHAN Raj Tezpur,<Media omitted>,2026,April,26,16,27